# STAGE 1: The Build (Requires SDK)
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
WORKDIR /src
COPY . .
# This command requires the SDK; it will fail in the aspnet-alpine image
RUN dotnet publish -c Release -o /app

# STAGE 2: The Final Image (Only Requires Runtime)
FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "Jenkins_App.dll"]

#docker build -f dockerfile.txt -t my-jenkins-first .
