pipeline {
    agent any

    stages {
        stage('Build') {
			agent{
				docker{
					image 'node:18-alpine'
					reuseNode true
				}
			}
            steps {
                sh '''
					echo "--- Listing Workspace Files ---"
					ls -la

					echo "--- Verifying .node version ---"
					npm --version
					node --version

					echo "--- Building Application ---"
					npm ci
					
					echo "--- Listing Workspace Files after build---"
					ls -la
					
					'''

            }
        }
    }
}
