pipeline {
    agent any

    stages {
		/*
        stage('Build') {
            agent {
                docker {
                    image 'mcr.microsoft.com/dotnet/sdk:8.0-alpine'
                    reuseNode true
                    args '''
                      -e DOTNET_CLI_HOME=/tmp/dotnet
                      -e DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
                      -e DOTNET_NOLOGO=true
                      -e NUGET_PACKAGES=/tmp/nuget
                    '''
                }
            }
            steps {
                sh '''
                    echo "--- Listing Workspace Files ---"
                    ls -la

                    echo "--- Verifying .NET SDK Version ---"
                    dotnet --version

                    echo "--- Building Application ---"
                    cd Jenkins_App
                    dotnet restore
                    dotnet build -c Release 
                    echo "--- Listing Workspace Files after build ---"
                    ls -la
                '''
            }
        }
		

		stage('Docker') {
            steps {
                sh 'docker build -f Jenkins_App/dockerfile.txt -t my-jenkins-first .'
            }
        }
		*/

		stage('Export Image') {
		    steps {
		        // This saves the image into a physical file
		        sh 'docker save -o my-jenkins-image.tar my-jenkins-first'
		        
		        // This makes the file available to download from the Jenkins UI
		        archiveArtifacts artifacts: 'my-jenkins-image.tar', fingerprint: true
		    }
		}
    }
}
